# -*- coding: utf-8 -*-
"""Copia de TelecomX_Churn_Analisis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R_lGESA9nESPcTpd1juWN_OoK9Obgti
"""

import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")



df.columns

df.info()

df.columns = df.columns.str.replace('.', '_')

df = df.rename(columns={
'customer_gender':'gender',
'customer_SeniorCitizen':'SeniorCitizen',
'customer_Partner':'Partner',
'customer_Dependents':'Dependents',
'phone_PhoneService':'PhoneService',
'phone_MultipleLines':'MultipleLines',
'internet_InternetService':'InternetService',
'internet_OnlineSecurity':'OnlineSecurity',
'internet_OnlineBackup':'OnlineBackup',
'internet_DeviceProtection':'DeviceProtection',
'internet_TechSupport':'TechSupport',
'internet_StreamingTV':'StreamingTV',
'internet_StreamingMovies':'StreamingMovies',
'account_Contract':'Contract',
'account_PaperlessBilling':'PaperlessBilling',
'account_PaymentMethod':'PaymentMethod',
'account_Charges_Monthly':'MonthlyCharges',
'account_Charges_Total':'TotalCharges'
})

df = df.rename(columns={'customer_tenure':'tenure'})

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df.isnull().sum()

df = df.dropna()

df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

df.head()

sns.countplot(x='Churn', data=df)

plt.title("Distribución de clientes que cancelan")
plt.xlabel("Churn")
plt.ylabel("Cantidad de clientes")

plt.show()

sns.countplot(x='Contract', hue='Churn', data=df)

plt.title("Churn por tipo de contrato")

plt.show()

sns.boxplot(x='Churn', y='tenure', data=df)

plt.title("Antigüedad del cliente vs Churn")

plt.show()

sns.boxplot(x='Churn', y='MonthlyCharges', data=df)

plt.title("Cargos mensuales vs Churn")

plt.show()

plt.figure(figsize=(10,5))

sns.countplot(x='PaymentMethod', hue='Churn', data=df)

plt.xticks(rotation=45)

plt.title("Churn por método de pago")

plt.show()

sns.countplot(x='InternetService', hue='Churn', data=df)

plt.title("Churn según tipo de servicio de internet")

plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')

plt.title("Matriz de correlación")

plt.show()

df.to_csv("telecom_churn_limpio.csv", index=False)